[build-system]
requires = ["setuptools>=61.0", "wheel", "Cython>=3.1", "numpy>=2.0"]
build-backend = "setuptools.build_meta"

[project]
name = "find-mfs"
version = "0.3.0"
description = "A Python package for finding molecular formula candidates from a mass and error window"
readme = "README.md"
license = {text = "GPL-3.0-or-later"}
authors = [
    {name = "Mostafa Hagar", email = "mostafa@150mL.com"}
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Chemistry",
]
keywords = ["mass spectrometry", "molecular formula", "accurate mass", "chemistry", "proteomics", "metabolomics"]
requires-python = ">=3.10,<3.14"

dependencies = [
    "molmass",
    "numpy>=2.0",
    "IsoSpecPy>=2.3",
    "scipy",
]

[project.optional-dependencies]
dev = ["pytest>=8.3.5", "pandas", "matplotlib", "jupyter", "maturin>=1.9"]
test = ["pytest>=8.3.5", "pandas"]

[project.urls]
Homepage = "https://github.com/mhagar/find-mfs"
Documentation = "https://github.com/mhagar/find-mfs#readme"
Repository = "https://github.com/mhagar/find-mfs"
Issues = "https://github.com/mhagar/find-mfs/issues"

[tool.setuptools.packages.find]
where = ["."]
include = ["find_mfs*"]


[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ty.src]
exclude = ["docs/"]

[dependency-groups]
dev = [
    {include-group = "test"},
    "build>=1.2.2.post1",
    "matplotlib",
    "jupyter",
    "maturin>=1.9",
    "sphinx>=8.1.3",
    "sphinx-autodoc-typehints>=3.0.1",
    "sphinx-rtd-theme>=3.0.2",
    "twine>=6.1.0",
]
test = [
    "pytest>=8.3.5",
    "pandas",
]
docs = [
    "sphinx>=8.1.3",
    "sphinx-autodoc-typehints>=3.0.1",
    "sphinx-rtd-theme>=3.0.2",
]
